# Root project information
sonar.projectKey=dsa-fdp-cmd-adaptor-sns
sonar.projectName=fdp/fdp-cmd-adaptor-sns
sonar.java.libraries=target/lib/*.jar
sonar.java.test.libraries=target/lib/*.jar
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml



# Modules
sonar.modules=cmd-adaptor-sns-common,cmd-adaptor-sns,cmd-adaptor-sns-integration-tests,cmd-adaptor-sns-test-common

# cmd-adaptor-sns-common
cmd-adaptor-sns-common.sonar.projectName=cmd-adaptor-sns-common
cmd-adaptor-sns-common.sonar.language=java
cmd-adaptor-sns-common.sonar.sources=src/main/java
cmd-adaptor-sns-common.sonar.java.binaries=target/classes
cmd-adaptor-sns-common.sonar.projectBaseDir=./cmd-adaptor-sns-common

# cmd-adaptor-sns
cmd-adaptor-sns.sonar.projectName=cmd-adaptor-sns
cmd-adaptor-sns.sonar.language=java
cmd-adaptor-sns.sonar.sources=src/main/java
cmd-adaptor-sns.sonar.tests=src/test/java
cmd-adaptor-sns.sonar.java.binaries=target/classes
cmd-adaptor-sns.sonar.projectBaseDir=./cmd-adaptor-sns
cmd-adaptor-sns.sonar.coverage.exclusions=**/CommandLineStartupRunner.java,**/TraceIdentityRecordTransformer.java,**/*CmdAdaptorApplication.java

# cmd-adaptor-sns-integration-tests
cmd-adaptor-sns-integration-tests.sonar.projectName=cmd-adaptor-sns-integration-tests
cmd-adaptor-sns-integration-tests.sonar.language=java
cmd-adaptor-sns-integration-tests.sonar.tests=src/test/java
cmd-adaptor-sns-integration-tests.sonar.java.binaries=.
cmd-adaptor-sns-integration-tests.sonar.projectBaseDir=./cmd-adaptor-sns-integration-tests

# cmd-adaptor-sns-test-common
cmd-adaptor-sns-test-common.sonar.projectName=cmd-adaptor-sns-test-common
cmd-adaptor-sns-test-common.sonar.language=java
cmd-adaptor-sns-test-common.sonar.tests=src/main/java
cmd-adaptor-sns-test-common.sonar.java.binaries=.
cmd-adaptor-sns-test-common.sonar.projectBaseDir=./cmd-adaptor-sns-test-common
