---
#############################################################################
# WARNING: This file is controlled via RepoSync, any changes made in the
# command adaptor repository will be overwritten by the RepoSync process.
# See https://gitlab.digital.homeoffice.gov.uk/dacc-de/dde-adaptor-reposync
#############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdp-cmd-adaptor-matching-delta-{{ .FDP_FEED_NAME }}
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    pipeline_name: fdp-{{ .FDP_FEED_NAME }}
    app: fdp-app
  {{if .WORKING_HOURS}}
  annotations:
    downscaler/uptime: {{ .WORKING_HOURS }}
  {{end}}
spec:
  replicas: {{ .FDP_CMD_ADAPTOR_MATCHING_DELTA_REPLICAS }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: fdp-cmd-adaptor-matching-delta-{{ .FDP_FEED_NAME }}
  template:
    metadata:
      labels:
        name: fdp-cmd-adaptor-matching-delta-{{ .FDP_FEED_NAME }}
        service: fdp-cmd-adaptor-matching-delta-{{ .FDP_FEED_NAME }}-svc
        pipeline_name: fdp-{{ .FDP_FEED_NAME }}
        app: fdp-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7107"
        prometheus.io/path: "/cmd-adaptor-matching-delta-{{ .FDP_APP_KAFKA_TOPIC_SUFFIX }}/prometheus"
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      imagePullSecrets:
        - name: "{{ .ARTIFACTORY_SECRET_NAME }}"
      volumes:
        - name: app-msk-app-keystore
          secret:
            secretName: app-msk-app-keystore
            defaultMode: 256
        - name: "{{ .FDP_APP_CDL_MSK_SECRET_NAME }}"
          secret:
            secretName: "{{ .FDP_APP_CDL_MSK_SECRET_NAME }}"
            defaultMode: 256
      containers:
        - name: fdp-cmd-adaptor-matching-delta-{{ .FDP_FEED_NAME }}
          image: docker.digital.homeoffice.gov.uk/dacc-aws/fdp-cmd-adaptor-matching-delta:{{ .CORE_TAG }}
          imagePullPolicy: Always
          command: ["java", "-jar", "/home/fdpuser/cmd-adaptor-matching-delta-exec.jar"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              memory: {{ .FDP_CMD_ADAPTOR_MEMORY_MAX }}
              cpu: {{ .FDP_CMD_ADAPTOR_CPU_MAX }}
            requests:
              memory: {{ .FDP_CMD_ADAPTOR_MEMORY_MIN }}
              cpu: {{ .FDP_CMD_ADAPTOR_CPU_MIN }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /cmd-adaptor-matching-delta-{{ .FDP_APP_KAFKA_TOPIC_SUFFIX }}/health/liveness
              port: 7107
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /cmd-adaptor-matching-delta-{{ .FDP_APP_KAFKA_TOPIC_SUFFIX }}/health/readiness
              port: 7107
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: "/home/fdpuser/fdp-msk/"
              name: app-msk-app-keystore
              readOnly: true
            - mountPath: "/home/fdpuser/fdp-app-cdl-msk/"
              name: "{{ .FDP_APP_CDL_MSK_SECRET_NAME }}"
              readOnly: true
          env:
{{if .FDP_APP_CDL_KAFKA_GROUP_ID}}
            - name: FDP_APP_CDL_KAFKA_GROUP_ID
              value: {{ .FDP_APP_CDL_KAFKA_GROUP_ID }}
{{end}}
            - name: _JAVA_OPTIONS
              value: "-Xms{{ .FDP_CMD_ADAPTOR_JAVA_MEMORY_MIN }} -Xmx{{ .FDP_CMD_ADAPTOR_JAVA_MEMORY_MAX }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .SPRING_PROFILES_ACTIVE }}"
            - name: FDP_KAFKA_STREAM_THREADS
              value: "{{ .FDP_KAFKA_STREAM_THREADS }}"
            - name: FDP_CMD_ADAPTOR_LOG_DIR
              value: "/home/fdpuser/persistent/logs/"
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: LOG_LEVEL
            - name: FDP_APP_MATCHING_AGGREGATE_TARGET
              value: {{ .FDP_APP_MATCHING_AGGREGATE_TARGET }}
            - name: FDP_KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: "{{ .FDP_KAFKA_BROKER_KEY_NAME }}"
            - name: FDP_KAFKA_SCHEMA_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: FDP_KAFKA_SCHEMA_REGISTRY_URL
            - name: FDP_APP_CDL_KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: "{{ .FDP_APP_CDL_KAFKA_BROKER_KEY_NAME }}"
            - name: FDP_APP_CDL_KAFKA_SCHEMA_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: "{{ .FDP_APP_CDL_KAFKA_SCHEMA_REGISTRY_URL_KEY_NAME }}"
            - name: FDP_APP_CDL_MSK_KEYSTORE_PATH
              value: "{{ .FDP_APP_CDL_MSK_KEYSTORE_PATH }}"
            - name: FDP_APP_CDL_MSK_KEYSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: "{{ .FDP_APP_CDL_MSK_KEYSTORE_PASS_KEY_NAME }}"
            - name: FDP_APP_KAFKA_TOPIC_SUFFIX
              value: {{ .FDP_APP_KAFKA_TOPIC_SUFFIX }}
            - name: FDP_APP_ADAPTOR_SHORT_NAME
              value: {{ .FDP_APP_MATCHING_NAME }}
            - name: FDP_APP_REDIS_NODES
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: "{{ .FDP_APP_REDIS_NODES_KEY_NAME }}"
            - name: FDP_APP_REDIS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: "{{ .FDP_APP_REDIS_AUTH_TOKEN_KEY_NAME }}"
        - name: fdp-jaeger-agent
          image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/dacc/jaegertracing/jaeger-agent:stable
          args: [ "--reporter.grpc.host-port=dns:///fdp-jaeger-collector-svc.{{ .JAEGER_NAMESPACE }}.svc.cluster.local:14250","--reporter.type=grpc","--processor.zipkin-compact.server-queue-size={{ .FDP_SPANS_QUEUE_SIZE }}" ]
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              memory: {{ .FDP_JAEGER_MEMORY_MAX }}
              cpu: {{ .FDP_JAEGER_CPU_MAX }}
            requests:
              memory: {{ .FDP_JAEGER_MEMORY_MIN }}
              cpu: {{ .FDP_JAEGER_CPU_MIN }}