@E2EService
Feature: Test SNS Command Adaptor - Service

  Scenario: ServiceRecord
    Given template StreamIngestRecord with the base file "sns-multiple.input"
    And template EoriCdlzLandingRecord with the base file "eori.input"
    When Eori CDLZ data is presented as per the template to the landing topic landing-413
    When Readiness health check is completed
    When StreamIngestRecord source data is presented with attributes as per the template to the input topic with prefix fdp-sns-input
    Then 6 Service SNAPSHOTS will be emitted
    And one Service record for "SNS-ITEM" with following attributes
      | metadata.identityRecord.poleId.v2.id                        | SNSENS:S={movementReferenceNumber{testId}IN1234{testId}}                                                                             |
      | metadata.identityRecord.type                                | S                                                                                                                                    |
      | metadata.sourceRecord.name                                  | SNSENS                                                                                                                               |
      | metadata.sourceRecord.shortName                             | SNS                                                                                                                                  |
      | metadata.sourceRecord.location                              | submissionIdmetadata.messageIdentification                                                                                           |
      | metadata.sourceRecord.id                                    | {movementReferenceNumber{testId}IN1234{testId}}                                                                                      |
      | metadata.sourceRecord.audit.createdBy                       | 0123456789                                                                                                                           |
      | metadata.sourceRecord.audit.createdTimestamp                | 2022-02-22T22:22:22.222Z                                                                                                             |
      | metadata.sourceRecord.audit.updatedBy                       | null                                                                                                                                 |
      | metadata.sourceRecord.audit.updatedTimestamp                | null                                                                                                                                 |
      | metadata.sourceRecord.audit.deletedBy                       | null                                                                                                                                 |
      | metadata.sourceRecord.audit.deletedTimestamp                | null                                                                                                                                 |
      | metadata.mappingRecord.name                                 | SNS-ITEM                                                                                                                             |
      | metadata.mappingRecord.version                              | mappingVersion                                                                                                                       |
      | metadata.complianceRecord.visibility                        | UNKNOWN                                                                                                                              |
      | metadata.complianceRecord.gscMarker                         | null                                                                                                                                 |
      | metadata.complianceRecord.retentionMarkerDays               | -1                                                                                                                                   |
      | snapshotTrigger                                             | null                                                                                                                                 |
      | type                                                        | CONSIGNMENT                                                                                                                          |
      | effectiveFromTimestamp                                      | null                                                                                                                                 |
      | effectiveToTimestamp                                        | null                                                                                                                                 |
      | dueTimestamp                                                | null                                                                                                                                 |
      | status                                                      | null                                                                                                                                 |
      | consignment.bagIDNumber                                     | null                                                                                                                                 |
      | consignment.commodityCode                                   | goods.goodsItems.commodityCode                                                                                                       |
      | consignment.declaredValue                                   | null                                                                                                                                 |
      | consignment.declaredValueCurrency                           | null                                                                                                                                 |
      | consignment.dimensionHeight                                 | null                                                                                                                                 |
      | consignment.dimensionLength                                 | null                                                                                                                                 |
      | consignment.dimensionUnit                                   | null                                                                                                                                 |
      | consignment.dimensionWidth                                  | null                                                                                                                                 |
      | consignment.exportDepotCode                                 | null                                                                                                                                 |
      | consignment.freightCharges                                  | null                                                                                                                                 |
      | consignment.freightCurrencyCode                             | null                                                                                                                                 |
      | consignment.handlingInstructions                            | null                                                                                                                                 |
      | consignment.mrnReference                                    | movementReferenceNumber{testId}                                                                                                      |
      | consignment.packingType                                     | null                                                                                                                                 |
      | consignment.parentShipmentReference                         | null                                                                                                                                 |
      | consignment.paymentType                                     | A                                                                                                                                    |
      | consignment.shed                                            | null                                                                                                                                 |
      | consignment.shipment.arrivalCountry                         | null                                                                                                                                 |
      | consignment.shipment.arrivalLocation                        | goods.goodsItems.0.loading.placeOfUnloading                                                                                          |
      | consignment.shipment.departureCountry                       | null                                                                                                                                 |
      | consignment.shipment.departureLocation                      | goods.goodsItems.0.loading.placeOfLoading                                                                                            |
      | consignment.shipment.goodsDescription                       | [goods.goodsItems.0.description]                                                                                                     |
      | consignment.shipment.numberOfPieces                         | null                                                                                                                                 |
      | consignment.shipment.shipmentReference                      | null                                                                                                                                 |
      | consignment.shipment.weight                                 | 13.24                                                                                                                                |
      | consignment.shipment.weightUnit                             | null                                                                                                                                 |
      | consignment.shipperNumber                                   | null                                                                                                                                 |
      | consignment.type                                            | ITEM                                                                                                                                 |
      | consignment.unitLoadingDevice                               | null                                                                                                                                 |
      | consignment.valueIndicator                                  | null                                                                                                                                 |
      | attributes.attrs.goods.goodsItems.unDangerousGoodsCode      | goods.goodsItems.0.unDangerousGoodsCode                                                                                              |
      | attributes.attrs.goods.goodsItems.commercialReferenceNumber | 123                                                                                                                                  |
      | attributes.attrs.itinerary.commercialReferenceNumber        | 789                                                                                                                                  |
      | attributes.attrs.header.ingestDateTime                      | 2022-02-22T22:22:22.222Z                                                                                                             |
      | attributes.attrs.itinerary.loading.placeOfLoading           | itinerary.loading.placeOfLoading                                                                                                     |
      | attributes.attrs.itinerary.loading.placeOfUnloading         | itinerary.loading.placeOfUnloading                                                                                                   |
      | attributes.attrs.itineraryLoadingLanguage                   | itinerary.loading.loadingLanguage                                                                                                    |
      | attributes.attrs.itineraryUnloadingLanguage                 | itinerary.loading.unloadingLanguage                                                                                                  |
      | attributes.attrs.itinerary.transportChargesMethodOfPayment  | D                                                                                                                                    |
      | attributes.attrs.descriptionLanguage                        | goods.goodsItems.0.descriptionLanguage                                                                                               |
      | attributes.attrs.packages                                   | goods.goodsItems.0.packages.0.kindOfPackages\|1\|1\|goods.goodsItems.0.packages.0.marks\|goods.goodsItems.0.packages.0.marksLanguage |
      | attributes.attrs.specialMentions                            | goods.goodsItems.0.specialMentions;goods.goodsItems.0.specialMentions1                                                               |
      | attributes.attrs.goodsitemsLoadingLanguage                  | goods.goodsItems.0.loading.loadingLanguage                                                                                           |
      | attributes.attrs.goodsitemsUnloadingLanguage                | goods.goodsItems.0.loading.unloadingLanguage                                                                                         |
      | attributes.attrs.declarantName                              | partyDeclarant                                                                                                                       |
      | attributes.attrs.mShipperName                               | PartyConsignor                                                                                                                       |
      | attributes.attrs.cShipperName                               | goodsConsignor                                                                                                                       |
      | attributes.attrs.cvrn                                       | vehicle002                                                                                                                           |
      | attributes.attrs.ctrn                                       | trailer002                                                                                                                           |
      | attributes.attrs.mvrn                                       | vehicle001                                                                                                                           |
      | attributes.attrs.mtrn                                       | trailer001                                                                                                                           |
      | attributes.attrs.documents                                  | \{"type": "704", "reference": "ABC1234567", "language": "English"\}                                                                  |
      | attributes.attrs.expectedDateTimeOfArrival                  | 2022-02-28T22:22:22.222Z                                                                                                             |
      | attributes.attrs.crn                                        | 123\|567                                                                                                                             |
    And one Service record for "SNS-ITEM" with following attributes
      | metadata.identityRecord.poleId.v2.id                       | SNSENS:S={movementReferenceNumber{testId}IN9876{testId}}                                                                             |
      | metadata.identityRecord.type                               | S                                                                                                                                    |
      | metadata.sourceRecord.name                                 | SNSENS                                                                                                                               |
      | metadata.sourceRecord.shortName                            | SNS                                                                                                                                  |
      | metadata.sourceRecord.location                             | submissionIdmetadata.messageIdentification                                                                                           |
      | metadata.sourceRecord.id                                   | {movementReferenceNumber{testId}IN9876{testId}}                                                                                      |
      | metadata.sourceRecord.audit.createdBy                      | 0123456789                                                                                                                           |
      | metadata.sourceRecord.audit.createdTimestamp               | 2022-02-22T22:22:22.222Z                                                                                                             |
      | metadata.sourceRecord.audit.updatedBy                      | null                                                                                                                                 |
      | metadata.sourceRecord.audit.updatedTimestamp               | null                                                                                                                                 |
      | metadata.sourceRecord.audit.deletedBy                      | null                                                                                                                                 |
      | metadata.sourceRecord.audit.deletedTimestamp               | null                                                                                                                                 |
      | metadata.mappingRecord.name                                | SNS-ITEM                                                                                                                             |
      | metadata.mappingRecord.version                             | mappingVersion                                                                                                                       |
      | metadata.complianceRecord.visibility                       | UNKNOWN                                                                                                                              |
      | metadata.complianceRecord.gscMarker                        | null                                                                                                                                 |
      | metadata.complianceRecord.retentionMarkerDays              | -1                                                                                                                                   |
      | snapshotTrigger                                            | null                                                                                                                                 |
      | type                                                       | CONSIGNMENT                                                                                                                          |
      | effectiveFromTimestamp                                     | null                                                                                                                                 |
      | effectiveToTimestamp                                       | null                                                                                                                                 |
      | dueTimestamp                                               | null                                                                                                                                 |
      | status                                                     | null                                                                                                                                 |
      | consignment.bagIDNumber                                    | null                                                                                                                                 |
      | consignment.commodityCode                                  | commodityCode                                                                                                                        |
      | consignment.declaredValue                                  | null                                                                                                                                 |
      | consignment.declaredValueCurrency                          | null                                                                                                                                 |
      | consignment.dimensionHeight                                | null                                                                                                                                 |
      | consignment.dimensionLength                                | null                                                                                                                                 |
      | consignment.dimensionUnit                                  | null                                                                                                                                 |
      | consignment.dimensionWidth                                 | null                                                                                                                                 |
      | consignment.exportDepotCode                                | null                                                                                                                                 |
      | consignment.freightCharges                                 | null                                                                                                                                 |
      | consignment.freightCurrencyCode                            | null                                                                                                                                 |
      | consignment.handlingInstructions                           | null                                                                                                                                 |
      | consignment.mrnReference                                   | movementReferenceNumber{testId}                                                                                                      |
      | consignment.packingType                                    | null                                                                                                                                 |
      | consignment.parentShipmentReference                        | null                                                                                                                                 |
      | consignment.paymentType                                    | B                                                                                                                                    |
      | consignment.shed                                           | null                                                                                                                                 |
      | consignment.shipment.arrivalCountry                        | null                                                                                                                                 |
      | consignment.shipment.arrivalLocation                       | goods.goodsItems.1.loading.placeOfUnloading                                                                                          |
      | consignment.shipment.departureCountry                      | null                                                                                                                                 |
      | consignment.shipment.departureLocation                     | goods.goodsItems.1.loading.placeOfLoading                                                                                            |
      | consignment.shipment.goodsDescription                      | [goods.goodsItems.1.description]                                                                                                     |
      | consignment.shipment.numberOfPieces                        | null                                                                                                                                 |
      | consignment.shipment.shipmentReference                     | null                                                                                                                                 |
      | consignment.shipment.weight                                | 16.63                                                                                                                                |
      | consignment.shipment.weightUnit                            | null                                                                                                                                 |
      | consignment.shipperNumber                                  | null                                                                                                                                 |
      | consignment.type                                           | ITEM                                                                                                                                 |
      | consignment.unitLoadingDevice                              | null                                                                                                                                 |
      | consignment.valueIndicator                                 | null                                                                                                                                 |
      | attributes.attrs.goods.goodsItems.unDangerousGoodsCode     | goods.goodsItems.1.unDangerousGoodsCode                                                                                              |
      | attributes.attrs.itinerary.commercialReferenceNumber       | 789                                                                                                                                  |
      | attributes.attrs.header.ingestDateTime                     | 2022-02-22T22:22:22.222Z                                                                                                             |
      | attributes.attrs.itinerary.loading.placeOfLoading          | itinerary.loading.placeOfLoading                                                                                                     |
      | attributes.attrs.itinerary.loading.placeOfUnloading        | itinerary.loading.placeOfUnloading                                                                                                   |
      | attributes.attrs.itineraryLoadingLanguage                  | itinerary.loading.loadingLanguage                                                                                                    |
      | attributes.attrs.itineraryUnloadingLanguage                | itinerary.loading.unloadingLanguage                                                                                                  |
      | attributes.attrs.itinerary.transportChargesMethodOfPayment | D                                                                                                                                    |
      | attributes.attrs.descriptionLanguage                       | goods.goodsItems.1.descriptionLanguage                                                                                               |
      | attributes.attrs.packages                                  | goods.goodsItems.1.packages.0.kindOfPackages\|1\|1\|goods.goodsItems.1.packages.0.marks\|goods.goodsItems.1.packages.0.marksLanguage |
      | attributes.attrs.specialMentions                           | goods.goodsItems.1.specialMentions                                                                                                   |
      | attributes.attrs.goodsitemsLoadingLanguage                 | goods.goodsItems.1.loading.loadingLanguage                                                                                           |
      | attributes.attrs.goodsitemsUnloadingLanguage               | goods.goodsItems.1.loading.unloadingLanguage                                                                                         |
      | attributes.attrs.declarantName                             | partyDeclarant                                                                                                                       |
      | attributes.attrs.mShipperName                              | PartyConsignor                                                                                                                       |
      | attributes.attrs.cShipperName                              | Location CShip                                                                                                                       |
      | attributes.attrs.cvrn                                      | vehicle003                                                                                                                           |
      | attributes.attrs.ctrn                                      | trailer003                                                                                                                           |
      | attributes.attrs.mvrn                                      | vehicle001                                                                                                                           |
      | attributes.attrs.mtrn                                      | trailer001                                                                                                                           |
      | attributes.attrs.documents.1                               | \{"type": "714", "reference": "HX-987", "language": "French"\}                                                                       |
      | attributes.attrs.documents.0                               | \{"type": "N704", "reference": "BH-123", "language": "German"\}                                                                      |
      | attributes.attrs.expectedDateTimeOfArrival                 | 2022-02-28T22:22:22.222Z                                                                                                             |
      | attributes.attrs.crn                                       | 456                                                                                                                                  |
    And one Service record for "SNS-ITEM" with following attributes
      | metadata.identityRecord.poleId.v2.id                       | SNSENS:S={movementReferenceNumber{testId}IN5555{testId}}                                                                             |
      | metadata.identityRecord.type                               | S                                                                                                                                    |
      | metadata.sourceRecord.name                                 | SNSENS                                                                                                                               |
      | metadata.sourceRecord.shortName                            | SNS                                                                                                                                  |
      | metadata.sourceRecord.location                             | submissionIdmetadata.messageIdentification                                                                                           |
      | metadata.sourceRecord.id                                   | {movementReferenceNumber{testId}IN5555{testId}}                                                                                      |
      | metadata.sourceRecord.audit.createdBy                      | 0123456789                                                                                                                           |
      | metadata.sourceRecord.audit.createdTimestamp               | 2022-02-22T22:22:22.222Z                                                                                                             |
      | metadata.sourceRecord.audit.updatedBy                      | null                                                                                                                                 |
      | metadata.sourceRecord.audit.updatedTimestamp               | null                                                                                                                                 |
      | metadata.sourceRecord.audit.deletedBy                      | null                                                                                                                                 |
      | metadata.sourceRecord.audit.deletedTimestamp               | null                                                                                                                                 |
      | metadata.mappingRecord.name                                | SNS-ITEM                                                                                                                             |
      | metadata.mappingRecord.version                             | mappingVersion                                                                                                                       |
      | metadata.complianceRecord.visibility                       | UNKNOWN                                                                                                                              |
      | metadata.complianceRecord.gscMarker                        | null                                                                                                                                 |
      | metadata.complianceRecord.retentionMarkerDays              | -1                                                                                                                                   |
      | snapshotTrigger                                            | null                                                                                                                                 |
      | type                                                       | CONSIGNMENT                                                                                                                          |
      | effectiveFromTimestamp                                     | null                                                                                                                                 |
      | effectiveToTimestamp                                       | null                                                                                                                                 |
      | dueTimestamp                                               | null                                                                                                                                 |
      | status                                                     | null                                                                                                                                 |
      | consignment.bagIDNumber                                    | null                                                                                                                                 |
      | consignment.commodityCode                                  | commodityCode                                                                                                                        |
      | consignment.declaredValue                                  | null                                                                                                                                 |
      | consignment.declaredValueCurrency                          | null                                                                                                                                 |
      | consignment.dimensionHeight                                | null                                                                                                                                 |
      | consignment.dimensionLength                                | null                                                                                                                                 |
      | consignment.dimensionUnit                                  | null                                                                                                                                 |
      | consignment.dimensionWidth                                 | null                                                                                                                                 |
      | consignment.exportDepotCode                                | null                                                                                                                                 |
      | consignment.freightCharges                                 | null                                                                                                                                 |
      | consignment.freightCurrencyCode                            | null                                                                                                                                 |
      | consignment.handlingInstructions                           | null                                                                                                                                 |
      | consignment.mrnReference                                   | movementReferenceNumber{testId}                                                                                                      |
      | consignment.packingType                                    | null                                                                                                                                 |
      | consignment.parentShipmentReference                        | null                                                                                                                                 |
      | consignment.paymentType                                    | B                                                                                                                                    |
      | consignment.shed                                           | null                                                                                                                                 |
      | consignment.shipment.arrivalCountry                        | null                                                                                                                                 |
      | consignment.shipment.arrivalLocation                       | goods.goodsItems.2.loading.placeOfUnloading                                                                                          |
      | consignment.shipment.departureCountry                      | null                                                                                                                                 |
      | consignment.shipment.departureLocation                     | goods.goodsItems.2.loading.placeOfLoading                                                                                            |
      | consignment.shipment.goodsDescription                      | [goods.goodsItems.2.description]                                                                                                     |
      | consignment.shipment.numberOfPieces                        | null                                                                                                                                 |
      | consignment.shipment.shipmentReference                     | null                                                                                                                                 |
      | consignment.shipment.weight                                | 16.63                                                                                                                                |
      | consignment.shipment.weightUnit                            | null                                                                                                                                 |
      | consignment.shipperNumber                                  | null                                                                                                                                 |
      | consignment.type                                           | ITEM                                                                                                                                 |
      | consignment.unitLoadingDevice                              | null                                                                                                                                 |
      | consignment.valueIndicator                                 | null                                                                                                                                 |
      | attributes.attrs.goods.goodsItems.unDangerousGoodsCode     | goods.goodsItems.2.unDangerousGoodsCode                                                                                              |
      | attributes.attrs.itinerary.commercialReferenceNumber       | 789                                                                                                                                  |
      | attributes.attrs.header.ingestDateTime                     | 2022-02-22T22:22:22.222Z                                                                                                             |
      | attributes.attrs.itinerary.loading.placeOfLoading          | itinerary.loading.placeOfLoading                                                                                                     |
      | attributes.attrs.itinerary.loading.placeOfUnloading        | itinerary.loading.placeOfUnloading                                                                                                   |
      | attributes.attrs.itineraryLoadingLanguage                  | itinerary.loading.loadingLanguage                                                                                                    |
      | attributes.attrs.itineraryUnloadingLanguage                | itinerary.loading.unloadingLanguage                                                                                                  |
      | attributes.attrs.itinerary.transportChargesMethodOfPayment | D                                                                                                                                    |
      | attributes.attrs.descriptionLanguage                       | goods.goodsItems.2.descriptionLanguage                                                                                               |
      | attributes.attrs.packages                                  | goods.goodsItems.2.packages.0.kindOfPackages\|1\|1\|goods.goodsItems.2.packages.0.marks\|goods.goodsItems.2.packages.0.marksLanguage |
      | attributes.attrs.specialMentions                           | goods.goodsItems.2.specialMentions                                                                                                   |
      | attributes.attrs.goodsitemsLoadingLanguage                 | goods.goodsItems.2.loading.loadingLanguage                                                                                           |
      | attributes.attrs.goodsitemsUnloadingLanguage               | goods.goodsItems.2.loading.unloadingLanguage                                                                                         |
      | attributes.attrs.declarantName                             | partyDeclarant                                                                                                                       |
      | attributes.attrs.mShipperName                              | PartyConsignor                                                                                                                       |
      | attributes.attrs.cShipperName                              | goodsConsignorName2{testId}                                                                                                          |
      | attributes.attrs.cvrn                                      | vehicle003                                                                                                                           |
      | attributes.attrs.ctrn                                      | trailer003                                                                                                                           |
      | attributes.attrs.mvrn                                      | vehicle001                                                                                                                           |
      | attributes.attrs.mtrn                                      | trailer001                                                                                                                           |
      | attributes.attrs.documents.1                               | \{"type": "714", "reference": "HX-987", "language": "French"\}                                                                       |
      | attributes.attrs.documents.0                               | \{"type": "N704", "reference": "BH-123", "language": "German"\}                                                                      |
      | attributes.attrs.expectedDateTimeOfArrival                 | 2022-02-28T22:22:22.222Z                                                                                                             |
      | attributes.attrs.crn                                       | 456                                                                                                                                  |
    And one Service record for "SNS-CONSIGNMENT" with following attributes
      | metadata.identityRecord.poleId.v2.id          | SNSENS:S={movementReferenceNumber{testId}789} |
      | metadata.identityRecord.type                  | S                                             |
      | metadata.sourceRecord.name                    | SNSENS                                        |
      | metadata.sourceRecord.shortName               | SNS                                           |
      | metadata.sourceRecord.location                | submissionIdmetadata.messageIdentification    |
      | metadata.sourceRecord.id                      | {movementReferenceNumber{testId}789}          |
      | metadata.sourceRecord.audit.createdBy         | 0123456789                                    |
      | metadata.sourceRecord.audit.createdTimestamp  | 2022-02-22T22:22:22.222Z                      |
      | metadata.sourceRecord.audit.updatedBy         | null                                          |
      | metadata.sourceRecord.audit.updatedTimestamp  | null                                          |
      | metadata.sourceRecord.audit.deletedBy         | null                                          |
      | metadata.sourceRecord.audit.deletedTimestamp  | null                                          |
      | metadata.mappingRecord.name                   | SNS-CONSIGNMENT                               |
      | metadata.mappingRecord.version                | mappingVersion                                |
      | metadata.complianceRecord.visibility          | UNKNOWN                                       |
      | metadata.complianceRecord.gscMarker           | null                                          |
      | metadata.complianceRecord.retentionMarkerDays | -1                                            |
      | snapshotTrigger                               | null                                          |
      | type                                          | CONSIGNMENT                                   |
      | effectiveFromTimestamp                        | null                                          |
      | effectiveToTimestamp                          | null                                          |
      | dueTimestamp                                  | null                                          |
      | status                                        | null                                          |
      | consignment.bagIDNumber                       | null                                          |
      | consignment.commodityCode                     | null                                          |
      | consignment.declaredValue                     | null                                          |
      | consignment.declaredValueCurrency             | null                                          |
      | consignment.dimensionHeight                   | null                                          |
      | consignment.dimensionLength                   | null                                          |
      | consignment.dimensionUnit                     | null                                          |
      | consignment.dimensionWidth                    | null                                          |
      | consignment.exportDepotCode                   | null                                          |
      | consignment.freightCharges                    | null                                          |
      | consignment.freightCurrencyCode               | null                                          |
      | consignment.handlingInstructions              | null                                          |
      | consignment.mrnReference                      | null                                          |
      | consignment.packingType                       | null                                          |
      | consignment.parentShipmentReference           | null                                          |
      | consignment.paymentType                       | null                                          |
      | consignment.shed                              | null                                          |
      | consignment.shipment.arrivalCountry           | null                                          |
      | consignment.shipment.arrivalLocation          | null                                          |
      | consignment.shipment.departureCountry         | null                                          |
      | consignment.shipment.departureLocation        | null                                          |
      | consignment.shipment.goodsDescription         | null                                          |
      | consignment.shipment.numberOfPieces           | null                                          |
      | consignment.shipment.shipmentReference        | 789                                           |
      | consignment.shipment.weight                   | null                                          |
      | consignment.shipment.weightUnit               | null                                          |
      | consignment.shipperNumber                     | null                                          |
      | consignment.type                              | ITEM                                          |
      | consignment.unitLoadingDevice                 | null                                          |
      | consignment.valueIndicator                    | null                                          |
      | attributes.attrs.header.ingestDateTime        | 2022-02-22T22:22:22.222Z                      |
    And one Service record for "SNS-CONSIGNMENT" with following attributes
      | metadata.identityRecord.poleId.v2.id          | SNSENS:S={movementReferenceNumber{testId}123} |
      | metadata.identityRecord.type                  | S                                             |
      | metadata.sourceRecord.name                    | SNSENS                                        |
      | metadata.sourceRecord.shortName               | SNS                                           |
      | metadata.sourceRecord.location                | submissionIdmetadata.messageIdentification    |
      | metadata.sourceRecord.id                      | {movementReferenceNumber{testId}123}          |
      | metadata.sourceRecord.audit.createdBy         | 0123456789                                    |
      | metadata.sourceRecord.audit.createdTimestamp  | 2022-02-22T22:22:22.222Z                      |
      | metadata.sourceRecord.audit.updatedBy         | null                                          |
      | metadata.sourceRecord.audit.updatedTimestamp  | null                                          |
      | metadata.sourceRecord.audit.deletedBy         | null                                          |
      | metadata.sourceRecord.audit.deletedTimestamp  | null                                          |
      | metadata.mappingRecord.name                   | SNS-CONSIGNMENT                               |
      | metadata.mappingRecord.version                | mappingVersion                                |
      | metadata.complianceRecord.visibility          | UNKNOWN                                       |
      | metadata.complianceRecord.gscMarker           | null                                          |
      | metadata.complianceRecord.retentionMarkerDays | -1                                            |
      | snapshotTrigger                               | null                                          |
      | type                                          | CONSIGNMENT                                   |
      | effectiveFromTimestamp                        | null                                          |
      | effectiveToTimestamp                          | null                                          |
      | dueTimestamp                                  | null                                          |
      | status                                        | null                                          |
      | consignment.bagIDNumber                       | null                                          |
      | consignment.commodityCode                     | null                                          |
      | consignment.declaredValue                     | null                                          |
      | consignment.declaredValueCurrency             | null                                          |
      | consignment.dimensionHeight                   | null                                          |
      | consignment.dimensionLength                   | null                                          |
      | consignment.dimensionUnit                     | null                                          |
      | consignment.dimensionWidth                    | null                                          |
      | consignment.exportDepotCode                   | null                                          |
      | consignment.freightCharges                    | null                                          |
      | consignment.freightCurrencyCode               | null                                          |
      | consignment.handlingInstructions              | null                                          |
      | consignment.mrnReference                      | null                                          |
      | consignment.packingType                       | null                                          |
      | consignment.parentShipmentReference           | null                                          |
      | consignment.paymentType                       | null                                          |
      | consignment.shed                              | null                                          |
      | consignment.shipment.arrivalCountry           | null                                          |
      | consignment.shipment.arrivalLocation          | null                                          |
      | consignment.shipment.departureCountry         | null                                          |
      | consignment.shipment.departureLocation        | null                                          |
      | consignment.shipment.goodsDescription         | null                                          |
      | consignment.shipment.numberOfPieces           | null                                          |
      | consignment.shipment.shipmentReference        | 123                                           |
      | consignment.shipment.weight                   | null                                          |
      | consignment.shipment.weightUnit               | null                                          |
      | consignment.shipperNumber                     | null                                          |
      | consignment.type                              | ITEM                                          |
      | consignment.unitLoadingDevice                 | null                                          |
      | consignment.valueIndicator                    | null                                          |
      | attributes.attrs.header.ingestDateTime        | 2022-02-22T22:22:22.222Z                      |
    And one Service record for "SNS-MOVEMENT" with following attributes
      | metadata.identityRecord.poleId.v2.id                                    | SNSENS:S={movementReferenceNumber{testId}}                                                                    |
      | metadata.identityRecord.type                                            | S                                                                                                             |
      | metadata.sourceRecord.name                                              | SNSENS                                                                                                        |
      | metadata.sourceRecord.shortName                                         | SNS                                                                                                           |
      | metadata.sourceRecord.location                                          | submissionIdmetadata.messageIdentification                                                                    |
      | metadata.sourceRecord.id                                                | {movementReferenceNumber{testId}}                                                                             |
      | metadata.sourceRecord.audit.createdBy                                   | 0123456789                                                                                                    |
      | metadata.sourceRecord.audit.createdTimestamp                            | 2022-02-22T22:22:22.222Z                                                                                      |
      | metadata.sourceRecord.audit.updatedBy                                   | null                                                                                                          |
      | metadata.sourceRecord.audit.updatedTimestamp                            | null                                                                                                          |
      | metadata.sourceRecord.audit.deletedBy                                   | null                                                                                                          |
      | metadata.sourceRecord.audit.deletedTimestamp                            | null                                                                                                          |
      | metadata.mappingRecord.name                                             | SNS-MOVEMENT                                                                                                  |
      | metadata.mappingRecord.version                                          | mappingVersion                                                                                                |
      | metadata.complianceRecord.visibility                                    | UNKNOWN                                                                                                       |
      | metadata.complianceRecord.gscMarker                                     | null                                                                                                          |
      | metadata.complianceRecord.retentionMarkerDays                           | -1                                                                                                            |
      | snapshotTrigger                                                         | null                                                                                                          |
      | type                                                                    | MOVEMENT                                                                                                      |
      | effectiveFromTimestamp                                                  | 2022-02-25T22:22:22.222Z                                                                                      |
      | effectiveToTimestamp                                                    | null                                                                                                          |
      | dueTimestamp                                                            | null                                                                                                          |
      | status                                                                  | null                                                                                                          |
      | movement.businessIdentifier                                             | movementReferenceNumber{testId}                                                                               |
      | movement.source                                                         | EORI765                                                                                                       |
      | movement.mode                                                           | RORO Accompanied Freight                                                                                      |
      | movement.actualDepartureTimestamp                                       | null                                                                                                          |
      | movement.type                                                           | PRE_ARRIVAL                                                                                                   |
      | attributes.attrs.specificCircumstancesIndicator                         | A                                                                                                             |
      | attributes.attrs.itinerary.officeOfFirstEntry.expectedDateTimeOfArrival | 2022-02-28T22:22:22.222Z                                                                                      |
      | attributes.attrs.itinerary.officeOfFirstEntry.reference                 | itinerary.officeOfFirstEntry.reference                                                                        |
      | attributes.attrs.goods.grossMass                                        | 50.0                                                                                                          |
      | attributes.attrs.goods.numberOfPackages                                 | 1                                                                                                             |
      | attributes.attrs.goods.numberOfItems                                    | 10                                                                                                            |
      | attributes.attrs.itinerary.conveyanceReference                          | itinerary.conveyanceReference                                                                                 |
      | attributes.attrs.amendment.place                                        | amendment.place                                                                                               |
      | attributes.attrs.amendment.language                                     | amendment.language                                                                                            |
      | attributes.attrs.declaration.localReferenceNumber                       | declaration.localReferenceNumber                                                                              |
      | attributes.attrs.declaration.place                                      | declaration.place                                                                                             |
      | attributes.attrs.declaration.language                                   | declaration.language                                                                                          |
      | attributes.attrs.declaration.officeOfLodgement                          | declaration.officeOfLodgement                                                                                 |
      | attributes.attrs.metadata.senderEORI                                    | EORI765                                                                                                       |
      | attributes.attrs.metadata.senderBranch                                  | metadata.senderBranch                                                                                         |
      | attributes.attrs.metadata.messageType                                   | IE313                                                                                                         |
      | attributes.attrs.metadata.receivedDateTime                              | 2022-02-23T22:22:22.222Z                                                                                      |
      | attributes.attrs.metadata.acceptedDateTime                              | 2022-02-24T22:22:22.222Z                                                                                      |
      | attributes.attrs.metadata.correlationId                                 | metadata.correlationId                                                                                        |
      | attributes.attrs.metadata.cnitDispatchDateTime                          | 2022-02-25T22:22:22.222Z                                                                                      |
      | attributes.attrs.header.ingestDateTime                                  | 2022-02-22T22:22:22.222Z                                                                                      |
      | attributes.attrs.countriesOfRouting                                     | itinerary.countriesOfRouting                                                                                  |
      | attributes.attrs.officeOfSubsequentEntry                                | itinerary.officesOfSubsequentEntry                                                                            |
      | attributes.attrs.seals                                                  | goods.seals.0.identity\|goods.seals.0.identityLanguage,goods.seals.1.identity\|goods.seals.1.identityLanguage |
