{
   "type":"record",
   "name":"LookupEoriValue",
   "namespace":"lookup",
   "fields":[
      {
         "name":"sendingDateTime",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"extractionType",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"traderName",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"streetAndNumber",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"city",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"postcode",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"dateOfRegistration",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"vatRegistrationNumber",
         "type":[
            "null",
            "string"
         ],
         "default":null
      },
      {
         "name":"principleEconomicActivity",
         "type":[
            "null",
            "string"
         ],
         "default":null
      }
   ]
}