<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.ho.dacc.fdp</groupId>
        <artifactId>fdp-cmd-adaptor-sns</artifactId>
        <version>2.8.1-SNAPSHOT</version>
    </parent>

    <artifactId>cmd-adaptor-sns</artifactId>
    <packaging>jar</packaging>


    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams-test-utils</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.ho.dacc.fdp</groupId>
            <artifactId>cmd-adaptor-sns-avro</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.ho.dacc.fdp</groupId>
            <artifactId>cmd-adaptor-sns-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.ho.dacc.fdp</groupId>
            <artifactId>cmd-adaptor-sns-test-common</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.ho.dacc.fdp</groupId>
            <artifactId>fdp-cmd-adaptor-sns-mapping</artifactId>
            <version>${mapping.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>uk.gov.ho.dacc.fdp</groupId>
            <artifactId>fdp-cmd-adaptor-test-common</artifactId>
            <version>${fdp-cmd-adaptor-test-common.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.ho.dacc.fdp</groupId>
            <artifactId>fdp-cmd-adaptor-mapping-template-lib</artifactId>
            <version>${mapping.lib.version}</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-logging</artifactId>
        </dependency>

        <dependency>
            <groupId>io.opentelemetry.javaagent</groupId>
            <artifactId>opentelemetry-javaagent</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <filtering>true</filtering>
                <directory>src/test/resources</directory>
            </testResource>
        </testResources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot-maven-plugin.version}</version>
                <configuration>
                    <finalName>${project.name}</finalName>
                    <classifier>exec</classifier>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>build-info</id>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>uk.gov.ho.dacc.fdp</groupId>
                <artifactId>fdp-cmd-adaptor-mapping-generator</artifactId>
                <version>${mapping.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>avro-mapping</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <outputDirectory>${project.basedir}/target/generated-sources</outputDirectory>
                    <configFileName>mappings/ConfigFileConfig.json</configFileName>
                    <outputPackage>uk.gov.ho.dacc.fdp</outputPackage>
                    <inputClass>uk.gov.ho.dsa.cdl.hmrc.snsens.StreamIngestRecord</inputClass>
                    <runLogInputClass>uk.gov.ho.dacc.fdp.runlog.SnsRunLogInput</runLogInputClass>
                    <outputClassMapping>
                        {
                        "Party":"uk.gov.ho.dacc.pole.party.PartyRecord",
                        "Object":"uk.gov.ho.dacc.pole.object.ObjectRecord",
                        "Location":"uk.gov.ho.dacc.pole.location.LocationRecord",
                        "Event":"uk.gov.ho.dacc.pole.event.EventRecord",
                        "Service":"uk.gov.ho.dacc.pole.service.ServiceRecord"
                        }
                    </outputClassMapping>
                    <exclusionLists>
                    </exclusionLists>
                    <customMapping>
                        {
                        "parentShipmentReference":"uk.gov.ho.dacc.fdp.custom.ParentShipmentReference",
                        "shipmentReferences":"uk.gov.ho.dacc.fdp.custom.ShipmentReference",
                        "trailerSplit":"uk.gov.ho.dacc.fdp.custom.TrailerSplit",
                        "trailerCSplit":"uk.gov.ho.dacc.fdp.custom.TrailerSplit",
                        "trailerIsNull":"uk.gov.ho.dacc.fdp.custom.TrailerPlateIsNull",
                        "fieldSplit":"uk.gov.ho.dacc.fdp.custom.VehiclePlateMapping",
                        "vehicleSplit":"uk.gov.ho.dacc.fdp.custom.VehicleSplit",
                        "vehicleCSplit":"uk.gov.ho.dacc.fdp.custom.VehicleSplit",
                        "DocumentsArrayIsEmpty":"uk.gov.ho.dacc.fdp.custom.DocumentsArrayIsEmpty",
                        "GetIdentityLength":"uk.gov.ho.dacc.fdp.custom.GetIdentityLength",
                        "Base64Encoder":"uk.gov.ho.dacc.fdp.custom.Base64Encoder",
                        "sealsValueConcat":"uk.gov.ho.dacc.fdp.custom.SealValueConcat",
                        "packageValueConcat":"uk.gov.ho.dacc.fdp.custom.PackageValueConcat",
                        "identityWhitespace":"uk.gov.ho.dacc.fdp.custom.IdentityWhitespace",
                        "identityWhitespace2":"uk.gov.ho.dacc.fdp.custom.IdentityWhitespace",
                        "getIdentityLength":"uk.gov.ho.dacc.fdp.custom.GetIdentityLength",
                        "getCIdentityLength":"uk.gov.ho.dacc.fdp.custom.GetIdentityLength",
                        "getImoNumber":"uk.gov.ho.dacc.fdp.custom.GetImoNumber",
                        "getCImoNumber":"uk.gov.ho.dacc.fdp.custom.GetImoNumber",
                        "consignmentNumber":"uk.gov.ho.dacc.fdp.custom.ConsignmentNumber",
                        "customSpecialMentions":"uk.gov.ho.dacc.fdp.custom.CustomSpecialMentions",
                        "countriesOfRoutingArray":"uk.gov.ho.dacc.fdp.custom.CountriesOfRoutingArray",
                        "officeOfSubsequentEntryArray":"uk.gov.ho.dacc.fdp.custom.OfficeOfSubsequentEntryArray",
                        "getContainerNumbers":"uk.gov.ho.dacc.fdp.custom.GetContainerNumbers"
                        }
                    </customMapping>
                    <firstValueList>
                        {
                        "Include":[
                        "all"
                        ],
                        "Exclude":[
                        "documents",
                        "specialMentions",
                        "kindOfPackages",
                        "containerNumber",
                        "numberOfPackages",
                        "numberOfPieces",
                        "marks",
                        "seals",
                        "commodityCode",
                        "unDangerousGoodsCode",
                        "commercialReferenceNumber",
                        "transportChargesMethodOfPayment",
                        "descriptionLanguage"
                        ]
                        }
                    </firstValueList>
                    <removeAttributeBody>true</removeAttributeBody>
                    <removeAttributeBodyPrefix>body</removeAttributeBodyPrefix>
                    <generateTransformersBuilders>true</generateTransformersBuilders>
                    <generateRunlog>true</generateRunlog>
                    <generateService>true</generateService>
                    <generateLookupClasses>false</generateLookupClasses>
                    <useCloners>true</useCloners>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>uk.gov.ho.dacc.fdp</groupId>
                        <artifactId>fdp-cmd-adaptor-mapping-template-lib</artifactId>
                        <version>${mapping.lib.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.ho.dacc.fdp</groupId>
                        <artifactId>fdp-cmd-adaptor-sns-mapping</artifactId>
                        <version>${mapping.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.coderplus.maven.plugins</groupId>
                <artifactId>copy-rename-maven-plugin</artifactId>
                <version>1.0.1</version>
                <executions>
                    <execution>
                        <id>rename-file</id>
                        <phase>package</phase>
                        <goals>
                            <goal>rename</goal>
                        </goals>
                        <configuration>
                            <sourceFile>target/lib/opentelemetry-javaagent-${opentelemetry.version}.jar</sourceFile>
                            <destinationFile>target/dependencies/opentelemetry-javaagent.jar</destinationFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>

    <repositories>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
        </repository>
    </repositories>
</project>
